services:
  - type: web
    name: playbeat-backend
    env: node
    plan: free
    buildCommand: yarn install
    startCommand: yarn start
    envVars:
      - key: ALLOWED_ORIGINS
        value: "https://front-wine-seven-35.vercel.app,https://ajjk.onrender.com,http://localhost:3000"
      - key: CLIENT_URL
        value: "https://front-wine-seven-35.vercel.app"
      - key: API_URL
        value: "https://ajjk.onrender.com"
